name: Deploy Images to GHCR

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  push-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: "Checkout GitHub Action"
        uses: actions/checkout@v4

      - name: "Login to GitHub Container Registry"
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "Build Image"
        run: |
          docker build . -t ghcr.io/fortnet-dev/bordmonitor-preview:latest -f docker/hosted-preview/Dockerfile
          docker push ghcr.io/fortnet-dev/bordmonitor-preview:latest

      - name: "Update instance"
        run: |
          curl -X POST ${{ secrets.PORTAINER_WEBHOOK_URL }}